import os
from groq import Groq
from dotenv import load_dotenv

# Load environment variables from .env
load_dotenv()

# Create Groq client
client = Groq(
    api_key=os.getenv("GROQ_API_KEY")
)


def generate_answer(prompt: str) -> str:
    """
    Send the constructed prompt to Groq and return the LLM response.

    Args:
        prompt: Prompt generated by prompt_builder.py

    Returns:
        Generated answer from the LLM.
    """

    response = client.chat.completions.create(
        model="openai/gpt-oss-20b",
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0.2,
    )

    return response.choices[0].message.content